apiVersion: v1
kind: Service
metadata: 
    name: react-app-service
spec:
  type: NodePort
  seleector: 
      app: myapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30017
  